# Generated by Django 2.2.2 on 2019-11-27 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191127_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 8, 19, 38, 973255, tzinfo=utc)),
        ),
    ]
