# Generated by Django 2.2.2 on 2019-11-27 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191127_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 9, 38, 31, 299457, tzinfo=utc)),
        ),
    ]
