# Generated by Django 2.2.2 on 2019-12-07 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191127_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 4, 54, 3, 439078, tzinfo=utc)),
        ),
    ]
